# Generated by Django 2.2.5 on 2020-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('optimism_1', models.TextField(max_length=255)),
                ('optimism_2', models.TextField(max_length=255)),
                ('neutralism_1', models.TextField()),
                ('neutralism_2', models.TextField()),
                ('neutralism_3', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Boxer',
        ),
    ]
