# Generated by Django 2.2.5 on 2020-12-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20201229_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='neutralism_1_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_2_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_2_moments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_2_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_2_times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_3_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='neutralism_4_team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='optimism_1_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='optimism_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='pessimism_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='pessimism_1_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='pessimism_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='pessimism_2_grade',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='neutralism_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='neutralism_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='neutralism_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='optimism_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='optimism_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
