# Generated by Django 2.2.5 on 2021-01-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20201231_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='loading_bar_optimism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='optimism_1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
