# Generated by Django 2.2.5 on 2021-01-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20210101_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='loading_bar_optimism',
        ),
    ]
