# Generated by Django 2.1.15 on 2021-01-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('opinion', models.TextField(blank=True, null=True)),
                ('idea_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Idea')),
            ],
        ),
    ]
