# Generated by Django 2.1.15 on 2021-01-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_opinions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinions',
            name='idea_opinion',
        ),
    ]
