# Generated by Django 2.1.15 on 2021-01-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210126_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='optimism_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
